$.Msg("ui manifest loaded");

const DUI_t = DotaDefaultUIElement_t;
let disabled = [
    DUI_t.DOTA_DEFAULT_UI_TOP_TIMEOFDAY,
    DUI_t.DOTA_DEFAULT_UI_TOP_HEROES,
    DUI_t.DOTA_DEFAULT_UI_FLYOUT_SCOREBOARD,
    //DUI_t.DOTA_DEFAULT_UI_ACTION_PANEL,
    DUI_t.DOTA_DEFAULT_UI_ACTION_MINIMAP,
    //DUI_t.DOTA_DEFAULT_UI_INVENTORY_PANEL,
    //DUI_t.DOTA_DEFAULT_UI_INVENTORY_SHOP,
    //DUI_t.DOTA_DEFAULT_UI_INVENTORY_ITEMS,
    //DUI_t.DOTA_DEFAULT_UI_INVENTORY_QUICKBUY,
    DUI_t.DOTA_DEFAULT_UI_INVENTORY_COURIER,
    DUI_t.DOTA_DEFAULT_UI_INVENTORY_PROTECT,
    //DUI_t.DOTA_DEFAULT_UI_INVENTORY_GOLD,
    DUI_t.DOTA_DEFAULT_UI_SHOP_SUGGESTEDITEMS,
    DUI_t.DOTA_DEFAULT_UI_SHOP_COMMONITEMS,
    DUI_t.DOTA_DEFAULT_UI_HERO_SELECTION_TEAMS,
    //DUI_t.DOTA_DEFAULT_UI_HERO_SELECTION_GAME_NAME,
    DUI_t.DOTA_DEFAULT_UI_HERO_SELECTION_CLOCK,
    DUI_t.DOTA_DEFAULT_UI_HERO_SELECTION_HEADER,
    //DUI_t.DOTA_DEFAULT_UI_TOP_MENU_BUTTONS,
    DUI_t.DOTA_DEFAULT_UI_TOP_BAR_BACKGROUND,
    DUI_t.DOTA_DEFAULT_UI_TOP_BAR_RADIANT_TEAM,
    DUI_t.DOTA_DEFAULT_UI_TOP_BAR_DIRE_TEAM,
    DUI_t.DOTA_DEFAULT_UI_TOP_BAR_SCORE,
    //DUI_t.DOTA_DEFAULT_UI_ENDGAME,
    DUI_t.DOTA_DEFAULT_UI_ENDGAME_CHAT,
    DUI_t.DOTA_DEFAULT_UI_QUICK_STATS,
    DUI_t.DOTA_DEFAULT_UI_PREGAME_STRATEGYUI,
    DUI_t.DOTA_DEFAULT_UI_KILLCAM,
    DUI_t.DOTA_DEFAULT_UI_FIGHT_RECAP,
    DUI_t.DOTA_DEFAULT_UI_TOP_BAR,
    DUI_t.DOTA_DEFAULT_UI_CUSTOMUI_BEHIND_HUD_ELEMENTS,
    DUI_t.DOTA_DEFAULT_UI_AGHANIMS_STATUS,
    DUI_t.DOTA_DEFAULT_UI_ELEMENT_COUNT,
];

for (let UI of disabled)
    GameUI.SetDefaultUIEnabled(UI, false);